{{- if .Values.mapproxy.enabled -}}

{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $replicaCount := .Values.mapproxy.replicaCount }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-deployment
  annotations:
    collectord.io/index: {{ quote .Values.splunkIndex }}
    collectord.io/output: splunk
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "mapproxy.environment" . }}
    release: {{ $releaseName }}
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  {{- template "mapproxy-chart.mapproxy-bundle" (merge (dict "releaseName" $releaseName "chartName" $chartName "replicaCount" $replicaCount "resources" .Values.mapproxy.resources) .)}}
{{- end -}}
